universe=vanilla
log=log/$(Cluster)_$(Process)_$(file).log
output=out/$(Cluster)_$(Process)_$(file).out
error=err/$(Cluster)_$(Process)_$(file).err
executable=./bill2.sh
arguments=$(file)
should_transfer_files=YES
transfer_input_files=$(file),logs/$(file).out,bill.R,http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz
when_to_transfer_output=ON_EXIT
request_cpus=1
request_memory=8GB
request_disk=16GB
queue file from logs/file